name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f29cd8cb0219949ba161857fb18ddcc323e79a1534caae28b5e9420e53cccc58"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
