name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7b7c3aa30a7b2948fb265f52315d517d8002f70e5e1792e2204f714318f4b03"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
