name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebc51b891ec43bca31d7f02d8e47506cee2c1eab852ed7e9b56fec931eae0941"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
