name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e94244a5a48baf943b8ce693b01263ab0d99336efbc7fbdb4aa62a2ce5a38a8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
